# Generated by Django 4.2.8 on 2025-12-23 08:42

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_property_google_map_url_property_tags_houserule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to=core.models.get_upload_to)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('protected', models.BooleanField(default=False)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedia Files',
            },
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room_type',
        ),
        migrations.DeleteModel(
            name='CommunityMedia',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
