# Generated by Django 4.2.8 on 2025-12-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_multimedia_remove_roomimage_room_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houserule',
            options={'verbose_name_plural': 'House Rules'},
        ),
        migrations.AlterUniqueTogether(
            name='houserule',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PropertyHouseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('house_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.houserule')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.property')),
            ],
            options={
                'db_table': 'property_house_rules',
                'ordering': ['order'],
                'unique_together': {('property', 'house_rule')},
            },
        ),
        migrations.RemoveField(
            model_name='houserule',
            name='order',
        ),
        migrations.RemoveField(
            model_name='houserule',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='house_rules',
            field=models.ManyToManyField(related_name='properties', through='core.PropertyHouseRule', to='core.houserule'),
        ),
    ]
